<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="DESKTOP-LKM5JTJ" name="com.qa.realerp.tests.LoginPageTest" tests="4" failures="1" timestamp="04 Jan 2021 15:27:16 GMT" time="9.537" errors="0">
  <testcase name="verifyPageTitleTest" time="0.026" classname="com.qa.realerp.tests.LoginPageTest">
    <failure type="java.lang.AssertionError" message="expected [Login | RealERP1] but found [Login | RealERP]">
      <![CDATA[java.lang.AssertionError: expected [Login | RealERP1] but found [Login | RealERP]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.qa.realerp.tests.LoginPageTest.verifyPageTitleTest(LoginPageTest.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyPageTitleTest -->
  <testcase name="verifyForgotPasswordLinkTest" time="0.000" classname="com.qa.realerp.tests.LoginPageTest">
    <skipped/>
  </testcase> <!-- verifyForgotPasswordLinkTest -->
  <testcase name="verifyValidLoginTest" time="9.511" classname="com.qa.realerp.tests.LoginPageTest"/>
  <testcase name="verifyInvalidLogin" classname="com.qa.realerp.tests.LoginPageTest">
    <skipped/>
  </testcase> <!-- verifyInvalidLogin -->
</testsuite> <!-- com.qa.realerp.tests.LoginPageTest -->
